package com.quillo.app.document

import android.graphics.*
import android.graphics.pdf.PdfDocument
import android.util.Base64
import com.quillo.app.document.layout.*
import java.io.*
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

object NativeDocxExporter {
    private const val W="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
    private const val R="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
    private fun esc(s:String)=s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;")
    private fun tw(px:Int)=(px*15).coerceAtLeast(0)
    private data class Media(val name:String,val bytes:ByteArray,val rid:String,val ext:String)
    fun write(document:QuilloDocument,out:OutputStream){
        val media=mutableListOf<Media>(); val hyperlinks=linkedMapOf<String,String>(); var nextImage=1; var nextRid=10
        fun runXml(r:TextRun):String {
            val props=(if(r.bold)"<w:b/>" else "")+(if(r.italic)"<w:i/>" else "")+(if(r.underline)"<w:u w:val=\"single\"/>" else "")+(if(r.strike)"<w:strike/>" else "")+"<w:rFonts w:ascii=\"${esc(r.fontFamily)}\" w:hAnsi=\"${esc(r.fontFamily)}\"/><w:sz w:val=\"${(r.fontSizePx*1.5f).toInt()}\"/>"
            val content=when {
                r.field!=null -> { val instr=when(r.field!!){WordField.PAGE->"PAGE";WordField.NUM_PAGES->"NUMPAGES";WordField.DATE->"DATE";WordField.TIME->"TIME";WordField.FILE_NAME->"FILENAME"}; "<w:r><w:fldChar w:fldCharType=\"begin\"/></w:r><w:r><w:instrText xml:space=\"preserve\"> $instr </w:instrText></w:r><w:r><w:fldChar w:fldCharType=\"separate\"/></w:r><w:r><w:t>${esc(r.text)}</w:t></w:r><w:r><w:fldChar w:fldCharType=\"end\"/></w:r>" }
                r.noteId!=null && r.noteKind==NoteKind.FOOTNOTE -> "<w:r><w:rPr>$props</w:rPr><w:footnoteReference w:id=\"${r.noteId}\"/></w:r>"
                r.noteId!=null && r.noteKind==NoteKind.ENDNOTE -> "<w:r><w:rPr>$props</w:rPr><w:endnoteReference w:id=\"${r.noteId}\"/></w:r>"
                else -> "<w:r><w:rPr>$props</w:rPr><w:t xml:space=\"preserve\">${esc(r.text)}</w:t></w:r>"
            }
            val commented=r.commentId?.let{"<w:commentRangeStart w:id=\"$it\"/>$content<w:commentRangeEnd w:id=\"$it\"/><w:r><w:commentReference w:id=\"$it\"/></w:r>"} ?: content
            return r.hyperlink?.let { url -> val rid=hyperlinks.getOrPut(url){"rId${nextRid++}"}; "<w:hyperlink r:id=\"$rid\" history=\"1\">$commented</w:hyperlink>" } ?: commented
        }
        fun imageXml(b:ImageBlock):String { val m=Regex("data:image/([^;]+);base64,(.*)",RegexOption.DOT_MATCHES_ALL).matchEntire(b.source)?:return "<w:p><w:r><w:t>[Image]</w:t></w:r></w:p>"; val ext=if(m.groupValues[1].contains("jpeg"))"jpg" else "png"; val bytes=runCatching{Base64.decode(m.groupValues[2],Base64.DEFAULT)}.getOrNull()?:return "<w:p/>"; val rid="rId${nextRid++}";val name="image${nextImage++}.$ext";media+=Media(name,bytes,rid,ext);val cx=b.widthPx.toLong()*9525;val cy=b.heightPx.toLong()*9525; val drawingBody="""<wp:extent cx="$cx" cy="$cy"/><wp:docPr id="${nextImage}" name="Picture"/><a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:nvPicPr><pic:cNvPr id="0" name="$name"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="$rid"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="$cx" cy="$cy"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic>"""; val wp=if(b.placement==ImagePlacement.ANCHORED){val wrap=when(b.wrap){ImageWrap.SQUARE->"<wp:wrapSquare wrapText=\"bothSides\"/>";ImageWrap.TIGHT->"<wp:wrapTight wrapText=\"bothSides\"><wp:wrapPolygon edited=\"0\"><wp:start x=\"0\" y=\"0\"/><wp:lineTo x=\"21600\" y=\"0\"/><wp:lineTo x=\"21600\" y=\"21600\"/><wp:lineTo x=\"0\" y=\"21600\"/><wp:lineTo x=\"0\" y=\"0\"/></wp:wrapPolygon></wp:wrapTight>";ImageWrap.TOP_BOTTOM->"<wp:wrapTopAndBottom/>";ImageWrap.BEHIND_TEXT->"<wp:wrapNone/>";ImageWrap.IN_FRONT_OF_TEXT->"<wp:wrapNone/>"};"<wp:anchor xmlns:wp=\"http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing\" behindDoc=\"${if(b.wrap==ImageWrap.BEHIND_TEXT)1 else 0}\" allowOverlap=\"1\" layoutInCell=\"1\" relativeHeight=\"251658240\" simplePos=\"0\"><wp:simplePos x=\"0\" y=\"0\"/><wp:positionH relativeFrom=\"column\"><wp:posOffset>${b.horizontalPositionPx*9525}</wp:posOffset></wp:positionH><wp:positionV relativeFrom=\"paragraph\"><wp:posOffset>${b.verticalPositionPx*9525}</wp:posOffset></wp:positionV>$drawingBody$wrap</wp:anchor>"}else "<wp:inline xmlns:wp=\"http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing\" distT=\"0\" distB=\"0\" distL=\"0\" distR=\"0\">$drawingBody</wp:inline>"; return "<w:p><w:r><w:drawing>$wp</w:drawing></w:r></w:p>"
        }
        fun block(b:QuilloBlock):String=when(b){
            is ParagraphBlock->{ val num=b.list?.let{"<w:numPr><w:ilvl w:val=\"${it.level.coerceIn(0,8)}\"/><w:numId w:val=\"${if(it.kind==ListKind.NUMBERED)2 else 1}\"/></w:numPr>"}.orEmpty(); "<w:p><w:pPr>$num<w:jc w:val=\"${b.alignment.name.lowercase()}\"/></w:pPr>${b.runs.joinToString(""){runXml(it)}}</w:p>" }
            is BreakBlock->"<w:p><w:r><w:br w:type=\"page\"/></w:r></w:p>"
            is ImageBlock->imageXml(b)
            is TableBlock->"<w:tbl>"+b.rows.joinToString(""){row->"<w:tr>"+row.joinToString(""){c->val tcPr=buildString{append("<w:tcPr>");if(c.columnSpan>1)append("<w:gridSpan w:val=\"${c.columnSpan}\"/>");c.verticalMerge?.let{append("<w:vMerge w:val=\"${esc(it)}\"/>")};c.background?.removePrefix("#")?.let{append("<w:shd w:fill=\"$it\"/>")};append("</w:tcPr>")};"<w:tc>$tcPr${c.blocks.joinToString(""){block(it)}}</w:tc>"}+"</w:tr>"}+"</w:tbl>"
        }
        val headers=mutableListOf<Pair<String,String>>();val footers=mutableListOf<Pair<String,String>>()
        var globalBlock=0
        val body=document.sections.mapIndexed{idx,s->val hr="rIdH$idx";val fr="rIdF$idx";headers+=hr to s.header;footers+=fr to s.footer;s.blocks.joinToString(""){ b -> val bi=globalBlock++; var xml=block(b); document.bookmarks.filter{it.start.block==bi}.forEach{bm->xml="<w:bookmarkStart w:id=\"${bm.id}\" w:name=\"${esc(bm.name)}\"/>"+xml}; document.bookmarks.filter{it.end.block==bi}.forEach{bm->xml+= "<w:bookmarkEnd w:id=\"${bm.id}\"/>"}; document.revisions.filter{bi in it.start.block..it.end.block}.forEach{rv-> val tag=if(rv.kind==RevisionKind.INSERTION)"ins" else "del"; xml="<w:$tag w:id=\"${rv.id}\" w:author=\"${esc(rv.author)}\"${if(rv.timestamp.isNotBlank())" w:date=\"${esc(rv.timestamp)}\"" else ""}>$xml</w:$tag>"}; xml }+"<w:sectPr><w:headerReference w:type=\"default\" r:id=\"$hr\"/><w:footerReference w:type=\"default\" r:id=\"$fr\"/><w:pgSz w:w=\"${tw(s.page.widthPx)}\" w:h=\"${tw(s.page.heightPx)}\"/><w:pgMar w:top=\"${tw(s.page.marginTopPx)}\" w:right=\"${tw(s.page.marginRightPx)}\" w:bottom=\"${tw(s.page.marginBottomPx)}\" w:left=\"${tw(s.page.marginLeftPx)}\"/></w:sectPr>"}.joinToString("")
        val doc="""<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="$W" xmlns:r="$R"><w:body>$body</w:body></w:document>"""
        ZipOutputStream(out).use{z->fun put(n:String,s:String){z.putNextEntry(ZipEntry(n));z.write(s.toByteArray());z.closeEntry()};fun putB(n:String,b:ByteArray){z.putNextEntry(ZipEntry(n));z.write(b);z.closeEntry()}
            val defaults=media.map{it.ext}.distinct().joinToString(""){"<Default Extension=\"$it\" ContentType=\"image/${if(it=="jpg")"jpeg" else it}\"/>"}
            put("[Content_Types].xml","""<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/>$defaults<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/numbering.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>${headers.indices.joinToString(""){"<Override PartName=\"/word/header${it+1}.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml\"/>"}}${footers.indices.joinToString(""){"<Override PartName=\"/word/footer${it+1}.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml\"/>"}}${if(document.comments.isNotEmpty())"<Override PartName=\"/word/comments.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.comments+xml\"/>" else ""}${if(document.footnotes.isNotEmpty())"<Override PartName=\"/word/footnotes.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.footnotes+xml\"/>" else ""}${if(document.endnotes.isNotEmpty())"<Override PartName=\"/word/endnotes.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.endnotes+xml\"/>" else ""}</Types>""")
            put("_rels/.rels","""<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="$R/officeDocument" Target="word/document.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>""")
            put("word/document.xml",doc)
            val rels="<Relationship Id=\"rIdNumbering\" Type=\"$R/numbering\" Target=\"numbering.xml\"/>"+hyperlinks.entries.joinToString(""){"<Relationship Id=\"${it.value}\" Type=\"$R/hyperlink\" Target=\"${esc(it.key)}\" TargetMode=\"External\"/>"}+media.joinToString(""){"<Relationship Id=\"${it.rid}\" Type=\"$R/image\" Target=\"media/${it.name}\"/>"}+headers.mapIndexed{i,x->"<Relationship Id=\"${x.first}\" Type=\"$R/header\" Target=\"header${i+1}.xml\"/>"}.joinToString("")+footers.mapIndexed{i,x->"<Relationship Id=\"${x.first}\" Type=\"$R/footer\" Target=\"footer${i+1}.xml\"/>"}.joinToString("")+(if(document.comments.isNotEmpty())"<Relationship Id=\"rIdComments\" Type=\"$R/comments\" Target=\"comments.xml\"/>" else "")+(if(document.footnotes.isNotEmpty())"<Relationship Id=\"rIdFootnotes\" Type=\"$R/footnotes\" Target=\"footnotes.xml\"/>" else "")+(if(document.endnotes.isNotEmpty())"<Relationship Id=\"rIdEndnotes\" Type=\"$R/endnotes\" Target=\"endnotes.xml\"/>" else "")
            put("word/_rels/document.xml.rels","""<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">$rels</Relationships>""")
            put("word/numbering.xml","""<?xml version="1.0"?><w:numbering xmlns:w="$W"><w:abstractNum w:abstractNumId="0"><w:lvl w:ilvl="0"><w:numFmt w:val="bullet"/><w:lvlText w:val="•"/></w:lvl></w:abstractNum><w:abstractNum w:abstractNumId="1"><w:lvl w:ilvl="0"><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/></w:lvl></w:abstractNum><w:num w:numId="1"><w:abstractNumId w:val="0"/></w:num><w:num w:numId="2"><w:abstractNumId w:val="1"/></w:num></w:numbering>""")
            val pr=document.properties
            put("docProps/core.xml","""<?xml version="1.0"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/"><dc:title>${esc(pr.title)}</dc:title><dc:subject>${esc(pr.subject)}</dc:subject><dc:creator>${esc(pr.author)}</dc:creator><cp:keywords>${esc(pr.keywords)}</cp:keywords><dc:description>${esc(pr.description)}</dc:description><cp:category>${esc(pr.category)}</cp:category></cp:coreProperties>""")
            put("docProps/app.xml","""<?xml version="1.0"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"><Company>${esc(pr.company)}</Company><Manager>${esc(pr.manager)}</Manager><Application>Quillo</Application></Properties>""")
            media.forEach{putB("word/media/${it.name}",it.bytes)}
            headers.forEachIndexed{i,x->put("word/header${i+1}.xml","""<?xml version="1.0"?><w:hdr xmlns:w="$W"><w:p><w:r><w:t>${esc(x.second)}</w:t></w:r></w:p></w:hdr>""")}
            footers.forEachIndexed{i,x->put("word/footer${i+1}.xml","""<?xml version="1.0"?><w:ftr xmlns:w="$W"><w:p><w:r><w:t>${esc(x.second)}</w:t></w:r><w:r><w:tab/></w:r><w:r><w:fldChar w:fldCharType="begin"/><w:instrText> PAGE </w:instrText><w:fldChar w:fldCharType="end"/></w:r></w:p></w:ftr>""")}
            if(document.comments.isNotEmpty()) put("word/comments.xml","<?xml version=\"1.0\"?><w:comments xmlns:w=\"$W\">"+document.comments.joinToString(""){"<w:comment w:id=\"${it.id}\" w:author=\"${esc(it.author)}\"><w:p><w:r><w:t>${esc(it.text)}</w:t></w:r></w:p></w:comment>"}+"</w:comments>")
            if(document.footnotes.isNotEmpty()) put("word/footnotes.xml","<?xml version=\"1.0\"?><w:footnotes xmlns:w=\"$W\"><w:footnote w:id=\"-1\"><w:p/></w:footnote><w:footnote w:id=\"0\"><w:p/></w:footnote>"+document.footnotes.joinToString(""){"<w:footnote w:id=\"${it.id}\"><w:p><w:r><w:footnoteRef/></w:r><w:r><w:t>${esc(it.text)}</w:t></w:r></w:p></w:footnote>"}+"</w:footnotes>")
            if(document.endnotes.isNotEmpty()) put("word/endnotes.xml","<?xml version=\"1.0\"?><w:endnotes xmlns:w=\"$W\"><w:endnote w:id=\"-1\"><w:p/></w:endnote><w:endnote w:id=\"0\"><w:p/></w:endnote>"+document.endnotes.joinToString(""){"<w:endnote w:id=\"${it.id}\"><w:p><w:r><w:endnoteRef/></w:r><w:r><w:t>${esc(it.text)}</w:t></w:r></w:p></w:endnote>"}+"</w:endnotes>")
        }
    }
}

object NativePdfExporter {
    fun write(document:QuilloDocument,out:OutputStream){
        val layout=DocumentLayoutEngine().layout(document);val pdf=PdfDocument();val paint=Paint(Paint.ANTI_ALIAS_FLAG)
        layout.pages.forEachIndexed{i,p->val page=pdf.startPage(PdfDocument.PageInfo.Builder(p.widthPx.coerceAtLeast(1),p.heightPx.coerceAtLeast(1),i+1).create());val c=page.canvas;c.drawColor(Color.WHITE);paint.color=Color.DKGRAY;paint.textSize=11f;c.drawText(p.header,p.contentLeftPx.toFloat(),(p.contentTopPx/2f).coerceAtLeast(14f),paint)
            p.blocks.forEach{b->when(b){is LayoutParagraph->{var y=b.y+(b.lines.firstOrNull()?.height?:16f);b.lines.forEach{ln->paint.textSize=14f;paint.color=Color.BLACK;c.drawText(ln.text,b.x,y,paint);y+=ln.height}};is LayoutTable->{paint.style=Paint.Style.STROKE;c.drawRect(b.x,b.y,b.x+b.width,b.y+b.height,paint);paint.style=Paint.Style.FILL};else->{}}};paint.color=Color.DKGRAY;paint.textSize=11f;c.drawText("${p.footer}    ${i+1}",p.contentLeftPx.toFloat(),(p.heightPx-20).toFloat(),paint);pdf.finishPage(page)}
        pdf.writeTo(out);pdf.close()
    }
}
